[package]
name = "nokhwa-decoders"
version = "0.1.0"
edition = "2024"

[features]
ffmpeg = ["ffmpeg-the-third"]
yuyv = ["dcv-color-primitives", "yuv"]
mjpeg = ["zune-jpeg", "zune-core"]
luma = ["itertools"]
#static = ["ffmpeg-the-third/static"]
#async = []

[dependencies]
bytemuck = "1.23"

[dependencies.nokhwa-core]
version = "0.2"
path = "../nokhwa-core"

[dependencies.ffmpeg-the-third]
version = "3.0"
optional = true

[dependencies.yuv]
version = "0.8"
optional = true

[dependencies.dcv-color-primitives]
version = "0.7"
optional = true

[dependencies.zune-jpeg]
version = "0.5.0-rc7"
optional = true

[dependencies.zune-core]
version = "0.5.0-rc2"
optional = true

[dependencies.itertools]
version = "0.14.0"
optional = true

[dev-dependencies.image]
workspace = true
features = ["png", "jpeg", "avif"]
